/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as ProductsNewRouteImport } from './routes/products/new'
import { Route as OrdersNewRouteImport } from './routes/orders/new'
import { Route as ProductsUpdateIdRouteImport } from './routes/products/update/$id'
import { Route as OrdersUpdateIdRouteImport } from './routes/orders/update/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsUpdateIdRoute = ProductsUpdateIdRouteImport.update({
  id: '/products/update/$id',
  path: '/products/update/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersUpdateIdRoute = OrdersUpdateIdRouteImport.update({
  id: '/orders/update/$id',
  path: '/orders/update/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/orders/new': typeof OrdersNewRoute
  '/products/new': typeof ProductsNewRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/orders/update/$id': typeof OrdersUpdateIdRoute
  '/products/update/$id': typeof ProductsUpdateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/orders/new': typeof OrdersNewRoute
  '/products/new': typeof ProductsNewRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/orders/update/$id': typeof OrdersUpdateIdRoute
  '/products/update/$id': typeof ProductsUpdateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/orders/new': typeof OrdersNewRoute
  '/products/new': typeof ProductsNewRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/orders/update/$id': typeof OrdersUpdateIdRoute
  '/products/update/$id': typeof ProductsUpdateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/orders/new'
    | '/products/new'
    | '/orders'
    | '/products'
    | '/orders/update/$id'
    | '/products/update/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/orders/new'
    | '/products/new'
    | '/orders'
    | '/products'
    | '/orders/update/$id'
    | '/products/update/$id'
  id:
    | '__root__'
    | '/'
    | '/orders/new'
    | '/products/new'
    | '/orders/'
    | '/products/'
    | '/orders/update/$id'
    | '/products/update/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrdersNewRoute: typeof OrdersNewRoute
  ProductsNewRoute: typeof ProductsNewRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  OrdersUpdateIdRoute: typeof OrdersUpdateIdRoute
  ProductsUpdateIdRoute: typeof ProductsUpdateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/update/$id': {
      id: '/products/update/$id'
      path: '/products/update/$id'
      fullPath: '/products/update/$id'
      preLoaderRoute: typeof ProductsUpdateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/update/$id': {
      id: '/orders/update/$id'
      path: '/orders/update/$id'
      fullPath: '/orders/update/$id'
      preLoaderRoute: typeof OrdersUpdateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrdersNewRoute: OrdersNewRoute,
  ProductsNewRoute: ProductsNewRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  OrdersUpdateIdRoute: OrdersUpdateIdRoute,
  ProductsUpdateIdRoute: ProductsUpdateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
